# the web app
webserver:
  build: .
  ports:
    - "18888:8080"
  links:
    - database:database
  volumes:
    - ./config/:/usr/local/tomcat/conf/Catalina/localhost/
    - ./files/:/usr/local/labkey/files/

# the database
database:
  image: postgres:9.6.5-alpine
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: labkeydbpass
  volumes:
    - ./data/:/var/lib/postgresql/data/
    - ./config/postgres.conf:/var/lib/postgresql/data/postgresql.conf

# the search engine
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
  ports:
   - "9200:9200"
   - "9300:9300"
  environment:
    discovery.type: single-node
    xpack.security.enabled: "false"

# the search visualizatons
kibana:
  image: docker.elastic.co/kibana/kibana:5.6.11
  ports:
   - "5601:5601"
  environment:
    xpack.monitoring.ui.container.elasticsearch.enabled: "false"
  links:
    - elasticsearch


# the sync
## https://dzone.com/articles/cli-for-indexing-data-from-postgres-to-elasticsear
## import --tail --src_type=postgres --src_uri="postgresql://postgres:labkeydbpass@database:5432/labkey" "http://elasticsearch:9200/labkey"
sync:
  image: appbaseio/abc
  volumes:
    - ./abc:/root
  links:
    - elasticsearch
    - database:database
  command: import  --log.level=debug --src_type=postgres --src_uri="postgresql://postgres:labkeydbpass@database:5432/labkey" "http://elasticsearch:9200/labkey"
